name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Python Linter
      # You may pin to the exact commit or the version.
      # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        # Source file or directory
          source: $(git ls-files '*.py') # optional, default is .
        # Set strictness for lint [low, medium, high]
          strict: medium # optional, default is medium
    - name: Run python black code formatter
  # You may pin to the exact commit or the version.
  # uses: DataDog/action-py-black-formatter@4aedfc9477c7c02cc6154936d2df964bb014a226
      uses: DataDog/action-py-black-formatter@v2.3
      with:
        # Black additional input arguments.
        # additional_args: # optional, default is 
        # Exit code when black formatting errors are found [true, false]. Defaults to 'true'.

        fail_on_error: true # optional, default is true
        # Main branch of the repository to speed up incremental diff

        main_branch: main # optional, default is main
        # (--quiet) Don't emit non-error messages to stderr. Errors are still emitted; silence those with 2>/dev/null

        quiet_mode: false # optional, default is false
        # (--diff) Don't write the files back, just output a diff for each file on stdout.

        print_diff_mode: false # optional, default is false
        # (--check) Don't write the files back, just return the status. 
        # Return code 0 means nothing would change. 
        # Return code 1 means some files would be reformatted. 
        # Return code 123 means there was an internal error.

        check_mode: false # optional, default is false
        # Turn on if you only want to check changed files instead of all files.

        only_changed_files: false # optional, default is false
        # Sha of the commit to compare files to.

        # base_commit: # optional, default is 
